/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as KlasemenRouteImport } from './routes/klasemen'
import { Route as PemainRouteImport } from './routes/pemain'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as TimRouteImport } from './routes/tim'
import { Route as HasilMatchIdRouteImport } from './routes/hasil.$matchId'
import { Route as PemainPlayerIdRouteImport } from './routes/pemain.$playerId'
import { Route as TimTeamIdRouteImport } from './routes/tim.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const KlasemenRoute = KlasemenRouteImport.update({
  id: '/klasemen',
  path: '/klasemen',
  getParentRoute: () => rootRouteImport,
} as any)
const PemainRoute = PemainRouteImport.update({
  id: '/pemain',
  path: '/pemain',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilMatchIdRoute = HasilMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => HasilRoute,
} as any)
const PemainPlayerIdRoute = PemainPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PemainRoute,
} as any)
const TimTeamIdRoute = TimTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TimRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRouteWithChildren
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/pemain': typeof PemainRouteWithChildren
  '/statistik': typeof StatistikRoute
  '/tim': typeof TimRouteWithChildren
  '/hasil/$matchId': typeof HasilMatchIdRoute
  '/pemain/$playerId': typeof PemainPlayerIdRoute
  '/tim/$teamId': typeof TimTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRouteWithChildren
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/pemain': typeof PemainRouteWithChildren
  '/statistik': typeof StatistikRoute
  '/tim': typeof TimRouteWithChildren
  '/hasil/$matchId': typeof HasilMatchIdRoute
  '/pemain/$playerId': typeof PemainPlayerIdRoute
  '/tim/$teamId': typeof TimTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hasil': typeof HasilRouteWithChildren
  '/jadwal': typeof JadwalRoute
  '/klasemen': typeof KlasemenRoute
  '/pemain': typeof PemainRouteWithChildren
  '/statistik': typeof StatistikRoute
  '/tim': typeof TimRouteWithChildren
  '/hasil/$matchId': typeof HasilMatchIdRoute
  '/pemain/$playerId': typeof PemainPlayerIdRoute
  '/tim/$teamId': typeof TimTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/pemain'
    | '/statistik'
    | '/tim'
    | '/hasil/$matchId'
    | '/pemain/$playerId'
    | '/tim/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/pemain'
    | '/statistik'
    | '/tim'
    | '/hasil/$matchId'
    | '/pemain/$playerId'
    | '/tim/$teamId'
  id:
    | '__root__'
    | '/'
    | '/hasil'
    | '/jadwal'
    | '/klasemen'
    | '/pemain'
    | '/statistik'
    | '/tim'
    | '/hasil/$matchId'
    | '/pemain/$playerId'
    | '/tim/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HasilRoute: typeof HasilRouteWithChildren
  JadwalRoute: typeof JadwalRoute
  KlasemenRoute: typeof KlasemenRoute
  PemainRoute: typeof PemainRouteWithChildren
  StatistikRoute: typeof StatistikRoute
  TimRoute: typeof TimRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klasemen': {
      id: '/klasemen'
      path: '/klasemen'
      fullPath: '/klasemen'
      preLoaderRoute: typeof KlasemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemain': {
      id: '/pemain'
      path: '/pemain'
      fullPath: '/pemain'
      preLoaderRoute: typeof PemainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil/$matchId': {
      id: '/hasil/$matchId'
      path: '/$matchId'
      fullPath: '/hasil/$matchId'
      preLoaderRoute: typeof HasilMatchIdRouteImport
      parentRoute: typeof HasilRoute
    }
    '/pemain/$playerId': {
      id: '/pemain/$playerId'
      path: '/$playerId'
      fullPath: '/pemain/$playerId'
      preLoaderRoute: typeof PemainPlayerIdRouteImport
      parentRoute: typeof PemainRoute
    }
    '/tim/$teamId': {
      id: '/tim/$teamId'
      path: '/$teamId'
      fullPath: '/tim/$teamId'
      preLoaderRoute: typeof TimTeamIdRouteImport
      parentRoute: typeof TimRoute
    }
  }
}

interface HasilRouteChildren {
  HasilMatchIdRoute: typeof HasilMatchIdRoute
}

const HasilRouteChildren: HasilRouteChildren = {
  HasilMatchIdRoute: HasilMatchIdRoute,
}

const HasilRouteWithChildren = HasilRoute._addFileChildren(HasilRouteChildren)

interface PemainRouteChildren {
  PemainPlayerIdRoute: typeof PemainPlayerIdRoute
}

const PemainRouteChildren: PemainRouteChildren = {
  PemainPlayerIdRoute: PemainPlayerIdRoute,
}

const PemainRouteWithChildren =
  PemainRoute._addFileChildren(PemainRouteChildren)

interface TimRouteChildren {
  TimTeamIdRoute: typeof TimTeamIdRoute
}

const TimRouteChildren: TimRouteChildren = {
  TimTeamIdRoute: TimTeamIdRoute,
}

const TimRouteWithChildren = TimRoute._addFileChildren(TimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HasilRoute: HasilRouteWithChildren,
  JadwalRoute: JadwalRoute,
  KlasemenRoute: KlasemenRoute,
  PemainRoute: PemainRouteWithChildren,
  StatistikRoute: StatistikRoute,
  TimRoute: TimRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
